services:
  nginx:
    container_name: nginx 
    image: nginx:1.19.0-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
  redis:
    container_name: redis 
    image: redis:6.2
    ports:
     - 6379:6379